steps:
  - name: python
    entrypoint: python
    args: [ "-m", "pip", "install", "--upgrade", "pip" ]
  - name: python
    entrypoint: python
    args: [ "-m", "pip", "install", "dvc[gs]", "--user" ]
  - name: python
    entrypoint: python
    args: [ "-m", "dvc", "pull"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/train:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/train:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'ai',
      'custom-jobs',
      'create',
      '--region=europe-west1',
      '--display-name=train-$SHORT_SHA',
      '--worker-pool-spec=machine-type=n1-standard-8,accelerator-type=nvidia-tesla-v100,accelerator-count=1,replica-count=1,container-image-uri=gcr.io/$PROJECT_ID/train:$SHORT_SHA',
    ]
images:
  - gcr.io/$PROJECT_ID/train:$SHORT_SHA
