steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=dockerfiles/app.dockerfile'
      - '--context=.'
      - '--destination=gcr.io/$PROJECT_ID/app:latest'
      - '--cache=true'
options:
  machineType: 'N1_HIGHCPU_32'
